#!/usr/bin/env python3

import sys
import binascii
import logging
import os

from common_backup_utils import ConfigFile, BackupUtils, CryptoUtils

def main(args):
    logging.basicConfig(level=logging.DEBUG, filename="debug.log")
    
    if len(args) != 2:
        print(f"Usage {sys.argv[0]} backup config_file")
        print("")
        ConfigFile.print_configuration_sample()
        return

    bu = BackupUtils(sys.argv[1])

    if not bu.config.is_required_config_available():
        ConfigFile.print_configuration_sample()
        return

    bu.get_file_list()

    backup_dir = bu.config.get("LOCAL_PATH_TO_BACKUP")
    logging.debug(f"backup_dir = {backup_dir}")
    for pn in bu.file_list:
        full_local_path = os.path.join(backup_dir, pn)
        hb = CryptoUtils.calc_local_file_hash(full_local_path)
        logging.debug(f"{pn}:{hb.hex()}")


    bu.backup_files("todays")


if __name__ == "__main__":
    main(sys.argv)
