#!/usr/bin/env python3

import sys
import binascii
import logging
import os
import glob

from common_backup_utils import ConfigFile, BackupUtils, CryptoUtils

def main(args):
    logging.basicConfig(level=logging.DEBUG, filename="debug.log")
    
    if len(args) != 2:
        print(f"Usage {sys.argv[0]} backup config_file")
        print("")
        ConfigFile.print_configuration_sample()
        return

    bu = BackupUtils(sys.argv[1])

    if not bu.config.is_required_config_available():
        ConfigFile.print_configuration_sample()
        return

    bu.cache_last_backup_manifest()

    bu.get_file_list()

    bu.backup_files()


if __name__ == "__main__":
    main(sys.argv)
