#!/usr/bin/env python3

import sys
#import crypt
import binascii

from common_backup_utils import ConfigFile, BackupUtils, CryptoUtils

def main(args):
    if len(args) != 2:
        print(f"Usage {sys.argv[0]} config_file")
        print("")
        ConfigFile.print_configuration_sample()
        return

    cf = ConfigFile(sys.argv[1])

    if not cf.is_required_config_available():
        ConfigFile.print_configuration_sample()
        return

    backup_path = cf.get("LOCAL_PATH_TO_BACKUP")

    current_list_of_files = BackupUtils.get_file_list(backup_path)

    for pn in current_list_of_files:
        hb = CryptoUtils.calc_file_hash(pn)
        print(f"{pn}:{hb.hex()}")




if __name__ == "__main__":
    main(sys.argv)
